### ISSUE TITLE
IO::Socket send croaks on send fail due to getpeername + performance issue [rt.cpan.org #65045]

### ISSUE THREAD

**Issue by toddr** [Dual-Life/IO#17]
Migrated from [rt.cpan.org#65045](https://rt.cpan.org/Ticket/Display.html?id=65045) (status was 'new')

Requestors:
* killing@multiplay.co.uk

From killing@multiplay.co.uk on 2011-01-23 20:28:03:
```
Due to the way IO::Socket uses getpeername a simple failed send
can cause the call to croak instead of returning an error.

The reason for this is that getpeername can fail if a previous
connected tcp socket is reset by the peer. In this case the
send should return with a failure code and $! should indicated
the failure of ECONNRESET.

In addition the current code calls getpeername for every single
send call which is not required for connected sockets e.g. tcp.
For large numbers of sends this extra kernel call could be quite
a performance drain so it would be good to remove it and kill
two birds with one stone.

    Regards
    Steve

================================================
This e.mail is private and confidential between Multiplay (UK) Ltd. and the person or entity to whom it is addressed. In the event of misdirection, the recipient is prohibited from using, copying, printing or otherwise disseminating it or any information contained in it. 

In the event of misdirection, illegible or incomplete transmission please telephone +44 845 868 1337
or return the E.mail to postmaster@multiplay.co.uk.

```

**Comment by stefanb2** [comment]
I stumbled over the `IO::Socket::send()` implementation while investigating [SO question #55161627](https://stackoverflow.com/questions/55161627/):

```perl
sub peername {
    @_ == 1 or croak 'usage: $sock->peername()';
    my($sock) = @_;
    ${*$sock}{'io_socket_peername'} ||= getpeername($sock);
}
...
sub send {
...
    my $peer  = $_[3] || $sock->peername;

    croak 'send: Cannot determine peer address'
	 unless(defined $peer);

    my $r = defined(getpeername($sock))
	? send($sock, $_[1], $flags)
	: send($sock, $_[1], $flags, $peer);

    # remember who we send to, if it was successful
    ${*$sock}{'io_socket_peername'} = $peer
	if(@_ == 4 && defined $r);
```

Originally `getpeername()` wasn't called at all, i.e. the peer address passed in by the caller was honoured. [IO 1.12](https://github.com/Dual-Life/IO/commit/9ab5475c251cef966dcbb1380858ccc2c74c4b3d) changed this, but only explains the What and not the Why. I have been unable to find a better version control history entry for this change, i.e. it is either lost or didn't exist at all.

> Modified `IO::Socket::send` so not to pass 4 arguments to `send` if the socket is connected

It could be that this paragraph in the Linux `send(2)` man page is the reason behind the change:

> If `sendto()` is used on a connection-mode (`SOCK_STREAM`,  `SOCK_SEQPACKET`)
       socket,  the arguments `dest_addr` and `addrlen` are ignored **(and the error
       `EISCONN` may be returned when they are not `NULL` and `0`)**,  and  the  error
       `ENOTCONN`  is returned when the socket was not actually connected.

i.e. it would prevent a failure when `$socket->send($data, $flags, $peer)` is used on a connected connection-mode socket. But this breaks the behaviour for connection-less sockets, because `$peer` gets ignored:

```perl
#!/usr/bin/perl
use warnings;
use strict;

use IO::Socket::INET;
use Socket qw(pack_sockaddr_in);

my $client = IO::Socket::INET->new(
    PeerAddr => '127.0.0.1',
    PeerPort => 2222,
    Proto    => 'udp',
) or die "client socket: $!\n";

my $addr = pack_sockaddr_in(3333, inet_aton('127.0.0.1'));

$client->send('ABCD', 0)
    or die "IO::Socket::send() no addr: $!\n";
$client->send('ABCD', 0, $addr)
    or die "IO::Socket::send() with addr: $!\n";
send($client, 'ABCD', 0, $addr)
    or die "send() with addr: $!\n";

exit 0;
```

Test run wrapped in `strace`:

```sh
$ strace -e send,sendto,connect,socket perl dummy.pl
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_UDP) = 4
connect(4, {sa_family=AF_INET, sin_port=htons(2222), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
sendto(4, "ABCD", 4, 0, NULL, 0)        = 4
sendto(4, "ABCD", 4, 0, NULL, 0)        = 4
sendto(4, "ABCD", 4, 0, {sa_family=AF_INET, sin_port=htons(3333), sin_addr=inet_addr("127.0.0.1")}, 16) = 4
```

Wouldn't it make sense to change the implementation to

```perl
sub send {
    @_ >= 2 && @_ <= 4 or croak('usage: $sock->send(BUF, [FLAGS, [TO]])');
    my $sock  = $_[0];
    my $flags = $_[2] || 0;
    my $peer  = $_[3] || $sock->peername;

    croak('send: Cannot determine peer address')
	unless(defined $peer);

    my $r = ($sock->socktype == SOCK_DGRAM)
	? send($sock, $_[1], $flags, $peer)
	: send($sock, $_[1], $flags);

    # remember who we send to, if it was successful
    ${*$sock}{'io_socket_peername'} = $peer
	if(@_ == 4 && defined $r);

    $r;
}
```

which would also take care of the performance issue of calling `getpeername()` on every invocation. I'm not sure if the code would need to check for other socket types besides `SOCK_DGRAM`.

With that implementation I get for my test code:

```sh
$ strace -e send,sendto,connect,socket perl dummy.pl
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_UDP) = 4
connect(4, {sa_family=AF_INET, sin_port=htons(2222), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
sendto(4, "ABCD", 4, 0, {sa_family=AF_INET, sin_port=htons(2222), sin_addr=inet_addr("127.0.0.1")}, 16) = 4
sendto(4, "ABCD", 4, 0, {sa_family=AF_INET, sin_port=htons(3333), sin_addr=inet_addr("127.0.0.1")}, 16) = 4
sendto(4, "ABCD", 4, 0, {sa_family=AF_INET, sin_port=htons(3333), sin_addr=inet_addr("127.0.0.1")}, 16) = 4
```

**Comment by toddr** [comment]
> I have been unable to find a better version control history entry for this change, i.e. it is either lost or didn't exist at all.

Version control for IO is managed by perl 5 porters. What is on CPAN does not differ in any way from upstream.

https://perl5.git.perl.org/perl.git

git log dist/IO

**Comment by Leont** [comment]
This behavior does indeed sound unhelpful.

**Comment by toddr** [comment]
I've got a tuit to move these issues into P5P's RT but I've not found the time to do it :(

**Comment by stefanb2** [comment]
> Version control for IO is managed by perl 5 porters. What is on CPAN does not differ in any way from upstream.

I had looked at that too and it is even worse: just a [blob commit](https://perl5.git.perl.org/perl.git/commit/27d4819aa2398f978c433f7367bcf083183444c9?f=ext/IO/lib/IO/Socket.pm) :-(

**Comment by stefanb2** [comment]
I just realized that there is a 2nd problem: although `$peer` is ignored a successful `$socket->send($data, $flags, $peer)` still caches it as default peername. After that `$sock->peername` will report the new peer, although `$sock->send()` will never send any packets to that peer...

Anyway, I just finished copying the information into `perlbug`. I'll attach the ticket number ones it pops up.

**Comment by stefanb2** [comment]
FYI: [RT #133936](https://rt.perl.org/Ticket/Display.html?id=133936)

**Comment by toddr** [comment]
This is fixed upstream so closing here. A new release is due I guess.
